/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "XXXXX add your own ID",
    "aws_user_pools_web_client_id": "XXXXXXX Replace with your own",
    "oauth": {}
};


export default awsmobile;
